PREFIX mesure: <http://www.semanticweb.org/medja/ontologies/2025/10/untitled-ontology-3#>

SELECT ?lat ?long ?vitesse ?limite ?date
WHERE {
    ?m mesure:latitude ?lat ;
       mesure:longitude ?long ;
       mesure:vitesseMesuree ?vitesse ;
       mesure:vitesseLimite ?limite ;
       mesure:dateMesure ?date .

    FILTER(?vitesse > ?limite)
}
LIMIT 500
